kim-junghwan/README.md
=> add: init folder

jiHyeong/README.md
=> docs: README.md 수정

daegyul/README.md
머규 성공?
리뷰어 - 나 올렸음 확인좀..
어사인니스 - 작성자 누구임?
=> docs: README 파일 수정

BooomJin/문자열다루기기본.py
=> add: Programmers_문자열다루기기본

kim-junghwan/1008.py
=> add: 백준 1008

kim-junghwan/1152.py
=> add: 백준 1152

daegyul/SumDivisor.java
2022.01.24 
1일 1 알고리즘
Programmers_약수의합 제출합니다.
=> add: SumDivisor.java추가_Programmers_약수의합

jiHyeong/수박수박수박수?.cpp
https://programmers.co.kr/learn/courses/30/lessons/12922
=> add Programmers_수박수박수박수박수박수?.cpp

kim-junghwan/1157.py
=> add: 백준 1157

daegyul/DeleteSameNum.java
DeleteSameNum.java
프로그래머스_같은 숫자는 싫어
=> add: DeleteSameNum.java추가_Programmers_같은 숫자는 싫어

BooomJin/정수 내림차순으로 배치하기.py
join문법 생각하기.. 밑에 병합정렬을 직접쓰는경우 생각해보기!
=> add : Programmers 정수를 내림차순으로 배치하기

soobeom/programmers/level1/없는 숫자 더하기.swift
프로그래머스 level1 "없는 숫자 더하기" 문제 풀이
=> add: 없는 숫자 더하기

BooomJin/자연수 뒤집어 배열로 만들기.py
하... 이거 문제이해를 제대로 안해서 이상한짓을 많이했네요..ㅜㅜ  정렬을 왜했을까요..
=> add : Programmers 자연수_뒤집어_배열로_만들기

BooomJin/하샤드 수.py
if문을 안 쓸 수 있는 것을 써버렸다.. 조금 더 주의해보자
=> add : Programmers 하샤드 수

daegyul/SumDigitNum.java
=> add: SumDigitNum추가_Programmers_자리수 더하기

soobeom/programmers/level1/평균 구하기.swift
=> add: 평균 구하기

daegyul/CalcGCDLCM.java
CalcGCDLCM.java추가
프로그래머스_최대공약수와 최소공배수
=> add: CalcGCDLCM추가_Programmers_최대공약수와 최소공배수

BooomJin/나누어 떨어지는 숫자 배열.py
클린코드로 한번에 짤 수는 없을까? 그래도 다행인건 점점 알고리즘에 익숙해져서 괜찮아 푸는데는 익숙해지는 것 같다.
=> add : Programmers_나누어떨어지는숫자배열

BooomJin/모의고사.py
=> add : Programmers_모의고사

daegyul/CalcSquareRoot.java
CalcSquareRoot추가
프로그래머스_정수제곱근판별
Math클래스 sqrt메소드 활용
=> add: CalcSquareRoot추가_Programmers_정수제곱근판별

daegyul/StringHandling.java
StringHandling추가
프로그래머스_문자열다루기기본
정규표현식에 대해 좀 더 공부해봐야겠음
=> add: StringHandling추가_Programmers_문자열다루기기본

BooomJin/예산.py
=> add : Programmers_예산

daegyul/DescSortNum.java
DescSortNum추가
Programmers_정수 내림차순으로 배치하기
정렬 알고리즘 버블, 선택, 삽입 정렬도 같이 공부하게됐다.
=> add: DescSortNum추가_Programmers_정수 내림차순으로 배치하기

BooomJin/BackJoon2576.py
=> add : BackJoon_2576_홀수

daegyul/ReverseNum.java
add: ReverseNum
Programmers_자연수 뒤집어 배열로 만들기
=> add: ReverseNum추가_Programmers_자연수 뒤집어 배열로 만들기

daegyul/CalcKNum.java, daegyul/HidePhoneNumber.java
Programmers_핸드폰번호가리기 - HidePhoneNumber
Programmers_k번째 수 - CalcKNum
=> Programmers_핸드폰번호가리기, k번째 수

BooomJin/체육복.py
=> add : Programmers_체육복

daegyul/Harshadnumber.java
Harshadnumber추가
Programmers 하샤드 수
=> add: Harshadnumber추가_Programmers_하샤드 수

BooomJin/10039_평균점수.py
=> add : BackJoon10039_평균점수

daegyul/DivNumArray.java, daegyul/README.md
Programmers_나누어 떨어지는 숫자배열
DivNumArray.java
=> add: DivNumArray추가_Programmers_나누어 떨어지는 숫자배열

BooomJin/주식가격.py
=> add : Programmers_주식가격

BooomJin/BackJoon1181_단어정렬.py
=> add : BackJoon1181_단어정렬.py

daegyul/Marathon.java
Marathon.java
Programmers_완주하지 못한 선수
이클립스 상에서 for문의 if 조건문을 아래와같이 해도 정상적으로 결과가 나온다.
if(participant[i] !=completion[i])
하지만 프로그래머스에 제출하면 오류가 발생하여 오답으로 나오는데 해결방법으로는 
if(!participant[i].equals(completion[i]))
equals를 활용하여 비교하는 것이다.
=> add: Marathon추가_Programmers_완주하지 못한 선수

BooomJin/BackJoon1934최소공배수.py
=> Add : BackJoon1934

BooomJin/2022알고리즘/1_모험가길드_그리디문제
=> 그리디: 모험가길드

BooomJin/2022알고리즘/2_곱하기 혹은 더하기_그리디문제.py
=> 2번문제_곱하기혹은더하기_그리디

BooomJin/2022알고리즘/4_만들 수 없는 금액_그리디문제.py
=> 4번문제_만들 수 없는 금액_그리디문제

BooomJin/2022알고리즘/15_특정 거리의 도시 찾기_DFSBFS.py, BooomJin/2022알고리즘/16_연구소_DFSBFS.py, BooomJin/2022알고리즘/17_경쟁적 전염_DFSBFS.py, BooomJin/2022알고리즘/18_괄호 변환_DFSBFS.py, BooomJin/2022알고리즘/19_연산자 끼워 넣기_DFSBFS.py, BooomJin/2022알고리즘/20_감시 피하기_DFSBFS.py, BooomJin/2022알고리즘/21_인구이동_DFSBFS.py, BooomJin/2022알고리즘/22_블록 이동하기_BFSDFS.py, BooomJin/2022알고리즘/23_국영수_정렬문제.py, BooomJin/2022알고리즘/24_안테나_정렬문제.py, BooomJin/2022알고리즘/25_실패율_정렬문제.py, BooomJin/2022알고리즘/26_카드 정렬하기_정렬문제.py, BooomJin/2022알고리즘/27_정렬된 배열에서 특정 수의 개수 구하기_이진탐색문제.py, BooomJin/2022알고리즘/28_고정점 찾기_이진탐색문제.py, BooomJin/2022알고리즘/29_공유기 설치_이진탐색문제.py, BooomJin/2022알고리즘/30_가사 검색_이진탐색문제.py, BooomJin/2022알고리즘/31_금광_다이나믹프로그래밍문제.py, BooomJin/2022알고리즘/32_정수 삼각형_다이나믹프로그래밍문제.py, BooomJin/2022알고리즘/33_퇴사_다이나믹프로그래밍문제.py, BooomJin/2022알고리즘/34_병사 배치하기_다이나믹프로그래밍문제.py, BooomJin/2022알고리즘/35_못생긴 수_다이나믹프로그래밍문제.py, BooomJin/2022알고리즘/36_편집거리_다이나믹프로그래밍문제.py
DFSBFS_정렬_이진탐색_DP 문제들 정리 ( 이코테 )
=> add : DFSBFS_정렬_이진탐색_DP
